### ISSUE TITLE
Demo errors

### ISSUE THREAD

**Issue by thuster** [usnistgov/trojai-example#3]
I'm getting errors with the demo listed in the read me.  Looks like some default paths are wrong... this fixes most of the errors:
```
python example_trojan_detector.py \
--model_filepath=./model/model.pt \
--result_filepath=./output.txt \
--scratch_dirpath=./scratch/ \
--examples_dirpath ./model/clean_example_data \
--tokenizer_filepath tokenizers/MobileBERT-google-mobilebert-uncased.pt
```
I'm also getting a key error.  Looks like the config keys changed:
```
Traceback (most recent call last):
  File "example_trojan_detector.py", line 233, in <module>
    args.examples_dirpath)
  File "example_trojan_detector.py", line 125, in example_trojan_detector
    print('Source dataset filepath = "{}"'.format(config['data_filepath']))
KeyError: 'data_filepath'
```

**Comment by mmajurski** [comment]
That key exists as a courtesy on the test server, so you have a full filepath to the source dataset. When running against the training data the config only lists the source dataset name, since you could have downloaded it to any folder.

I have added a check to only print that line if the key exists.

Thanks,
